# Setup

title:            magical girl rem's site
description:      site of remilia alucard, world's first real magical girl.
url: https://remalucard.github.io
repository: remalucard/remalucard.github.io

permalink: pretty

# Configuration
plugins: 
- jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

# search function
search_enabled: false

# back to top
back_to_top: true
back_to_top_text: "back up please"

#edit ig?
gh_edit_link: false