# Setup

title:            magical girl rem's site
description:      site of remilia alucard, world's first real magical girl.

# Configuration
plugins: 
- jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs